### ISSUE TITLE
Restaurant View

### ISSUE THREAD

**Issue by mohitDeshpande** [fishsticks-humber/wunderbar-webapp#7]
- [x] create mockup on paper and submit image in marvel app
- [x] show mockup to the team
- [x] create react component 
- [x] open pull request and assign to everyone to review
- [x] CSS styling
- [ ] Maps
- [x] Reviews

**Comment by maxpvk** [comment]
Mockup done, check it out.

**Comment by mohitDeshpande** [comment]
Maps will be done as a part of another issue
